// Code generated by "infoblox-go-client-generator"; DO NOT EDIT.

package ibclient

import (
	. "github.com/onsi/gomega"
	"testing"
)

// TestIBObjectsGenerated_CommonMethods checks if common methods
// for each generated Infoblox object works as expected
func TestIBObjectsGenerated_CommonMethods(t *testing.T) {
	testCases := map[string]struct {
		obj                  IBObject
		expectedReturnFields []string
		expectedObjectType   string
	}{
		"Allendpoints": {
			obj:                  &Allendpoints{},
			expectedReturnFields: []string{},
			expectedObjectType:   "allendpoints",
		},
		"Allrecords": {
			obj:                  &Allrecords{},
			expectedReturnFields: []string{"comment", "name", "type", "view", "zone"},
			expectedObjectType:   "allrecords",
		},
		"Allrpzrecords": {
			obj:                  &Allrpzrecords{},
			expectedReturnFields: []string{"comment", "name", "type", "view", "zone"},
			expectedObjectType:   "allrpzrecords",
		},
		"Adminrole": {
			obj:                  &Adminrole{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "adminrole",
		},
		"Authpolicy": {
			obj:                  &Authpolicy{},
			expectedReturnFields: []string{"default_group", "usage_type"},
			expectedObjectType:   "authpolicy",
		},
		"Adminuser": {
			obj:                  &Adminuser{},
			expectedReturnFields: []string{"admin_groups", "comment", "name"},
			expectedObjectType:   "adminuser",
		},
		"Allnsgroup": {
			obj:                  &Allnsgroup{},
			expectedReturnFields: []string{"name", "type"},
			expectedObjectType:   "allnsgroup",
		},
		"AdAuthService": {
			obj:                  &AdAuthService{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "ad_auth_service",
		},
		"Approvalworkflow": {
			obj:                  &Approvalworkflow{},
			expectedReturnFields: []string{"approval_group", "submitter_group"},
			expectedObjectType:   "approvalworkflow",
		},
		"Awsrte53taskgroup": {
			obj:                  &Awsrte53taskgroup{},
			expectedReturnFields: []string{"account_id", "comment", "disabled", "name", "sync_status"},
			expectedObjectType:   "awsrte53taskgroup",
		},
		"Bfdtemplate": {
			obj:                  &Bfdtemplate{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "bfdtemplate",
		},
		"Awsuser": {
			obj:                  &Awsuser{},
			expectedReturnFields: []string{"access_key_id", "account_id", "name"},
			expectedObjectType:   "awsuser",
		},
		"Bulkhostnametemplate": {
			obj:                  &Bulkhostnametemplate{},
			expectedReturnFields: []string{"is_grid_default", "template_format", "template_name"},
			expectedObjectType:   "bulkhostnametemplate",
		},
		"CapacityReport": {
			obj:                  &CapacityReport{},
			expectedReturnFields: []string{"name", "percent_used", "role"},
			expectedObjectType:   "capacityreport",
		},
		"Bulkhost": {
			obj:                  &Bulkhost{},
			expectedReturnFields: []string{"comment", "prefix"},
			expectedObjectType:   "bulkhost",
		},
		"CertificateAuthservice": {
			obj:                  &CertificateAuthservice{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "certificate:authservice",
		},
		"Captiveportal": {
			obj:                  &Captiveportal{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "captiveportal",
		},
		"Cacertificate": {
			obj:                  &Cacertificate{},
			expectedReturnFields: []string{"distinguished_name", "issuer", "serial", "used_by", "valid_not_after", "valid_not_before"},
			expectedObjectType:   "cacertificate",
		},
		"DbObjects": {
			obj:                  &DbObjects{},
			expectedReturnFields: []string{"last_sequence_id", "object", "object_type", "unique_id"},
			expectedObjectType:   "db_objects",
		},
		"Csvimporttask": {
			obj:                  &Csvimporttask{},
			expectedReturnFields: []string{"action", "admin_name", "end_time", "file_name", "file_size", "import_id", "lines_failed", "lines_processed", "lines_warning", "on_error", "operation", "separator", "start_time", "status", "update_method"},
			expectedObjectType:   "csvimporttask",
		},
		"DdnsPrincipalcluster": {
			obj:                  &DdnsPrincipalcluster{},
			expectedReturnFields: []string{"comment", "group", "name", "principals"},
			expectedObjectType:   "ddns:principalcluster",
		},
		"DdnsPrincipalclusterGroup": {
			obj:                  &DdnsPrincipalclusterGroup{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "ddns:principalcluster:group",
		},
		"DeletedObjects": {
			obj:                  &DeletedObjects{},
			expectedReturnFields: []string{"object_type"},
			expectedObjectType:   "deleted_objects",
		},
		"Dhcpfailover": {
			obj:                  &Dhcpfailover{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "dhcpfailover",
		},
		"DhcpStatistics": {
			obj:                  &DhcpStatistics{},
			expectedReturnFields: []string{"dhcp_utilization", "dhcp_utilization_status", "dynamic_hosts", "static_hosts", "total_hosts"},
			expectedObjectType:   "dhcp:statistics",
		},
		"Dbsnapshot": {
			obj:                  &Dbsnapshot{},
			expectedReturnFields: []string{"comment", "timestamp"},
			expectedObjectType:   "dbsnapshot",
		},
		"Dhcpoptiondefinition": {
			obj:                  &Dhcpoptiondefinition{},
			expectedReturnFields: []string{"code", "name", "type"},
			expectedObjectType:   "dhcpoptiondefinition",
		},
		"DiscoveryCredentialgroup": {
			obj:                  &DiscoveryCredentialgroup{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "discovery:credentialgroup",
		},
		"CiscoiseEndpoint": {
			obj:                  &CiscoiseEndpoint{},
			expectedReturnFields: []string{"address", "disable", "resolved_address", "type", "version"},
			expectedObjectType:   "ciscoise:endpoint",
		},
		"Admingroup": {
			obj:                  &Admingroup{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "admingroup",
		},
		"DiscoveryDevicecomponent": {
			obj:                  &DiscoveryDevicecomponent{},
			expectedReturnFields: []string{"component_name", "description", "model", "serial", "type"},
			expectedObjectType:   "discovery:devicecomponent",
		},
		"DiscoveryDevice": {
			obj:                  &DiscoveryDevice{},
			expectedReturnFields: []string{"address", "name", "network_view"},
			expectedObjectType:   "discovery:device",
		},
		"DiscoveryDevicesupportbundle": {
			obj:                  &DiscoveryDevicesupportbundle{},
			expectedReturnFields: []string{"author", "integrated_ind", "name", "version"},
			expectedObjectType:   "discovery:devicesupportbundle",
		},
		"Dhcpoptionspace": {
			obj:                  &Dhcpoptionspace{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dhcpoptionspace",
		},
		"DiscoveryDeviceneighbor": {
			obj:                  &DiscoveryDeviceneighbor{},
			expectedReturnFields: []string{"address", "address_ref", "mac", "name"},
			expectedObjectType:   "discovery:deviceneighbor",
		},
		"DiscoveryDiagnostictask": {
			obj:                  &DiscoveryDiagnostictask{},
			expectedReturnFields: []string{"ip_address", "network_view", "task_id"},
			expectedObjectType:   "discovery:diagnostictask",
		},
		"DiscoveryDeviceinterface": {
			obj:                  &DiscoveryDeviceinterface{},
			expectedReturnFields: []string{"name", "type"},
			expectedObjectType:   "discovery:deviceinterface",
		},
		"DiscoverySdnnetwork": {
			obj:                  &DiscoverySdnnetwork{},
			expectedReturnFields: []string{"name", "network_view", "source_sdn_config"},
			expectedObjectType:   "discovery:sdnnetwork",
		},
		"Distributionschedule": {
			obj:                  &Distributionschedule{},
			expectedReturnFields: []string{"active", "start_time", "time_zone"},
			expectedObjectType:   "distributionschedule",
		},
		"Dns64group": {
			obj:                  &Dns64group{},
			expectedReturnFields: []string{"comment", "disable", "name"},
			expectedObjectType:   "dns64group",
		},
		"DiscoveryMemberproperties": {
			obj:                  &DiscoveryMemberproperties{},
			expectedReturnFields: []string{"discovery_member"},
			expectedObjectType:   "discovery:memberproperties",
		},
		"Discovery": {
			obj:                  &Discovery{},
			expectedReturnFields: []string{},
			expectedObjectType:   "discovery",
		},
		"Dtc": {
			obj:                  &Dtc{},
			expectedReturnFields: []string{},
			expectedObjectType:   "dtc",
		},
		"DiscoveryVrf": {
			obj:                  &DiscoveryVrf{},
			expectedReturnFields: []string{"device", "name", "network_view", "route_distinguisher"},
			expectedObjectType:   "discovery:vrf",
		},
		"DiscoveryGridproperties": {
			obj:                  &DiscoveryGridproperties{},
			expectedReturnFields: []string{"grid_name"},
			expectedObjectType:   "discovery:gridproperties",
		},
		"DtcCertificate": {
			obj:                  &DtcCertificate{},
			expectedReturnFields: []string{},
			expectedObjectType:   "dtc:certificate",
		},
		"DtcLbdn": {
			obj:                  &DtcLbdn{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:lbdn",
		},
		"DtcMonitorHttp": {
			obj:                  &DtcMonitorHttp{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:monitor:http",
		},
		"Discoverytask": {
			obj:                  &Discoverytask{},
			expectedReturnFields: []string{"discovery_task_oid", "member_name"},
			expectedObjectType:   "discoverytask",
		},
		"DtcMonitorPdp": {
			obj:                  &DtcMonitorPdp{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:monitor:pdp",
		},
		"DtcMonitorSip": {
			obj:                  &DtcMonitorSip{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:monitor:sip",
		},
		"DtcMonitorSnmp": {
			obj:                  &DtcMonitorSnmp{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:monitor:snmp",
		},
		"DtcAllrecords": {
			obj:                  &DtcAllrecords{},
			expectedReturnFields: []string{"comment", "dtc_server", "type"},
			expectedObjectType:   "dtc:allrecords",
		},
		"DtcMonitor": {
			obj:                  &DtcMonitor{},
			expectedReturnFields: []string{"comment", "name", "type"},
			expectedObjectType:   "dtc:monitor",
		},
		"DiscoveryStatus": {
			obj:                  &DiscoveryStatus{},
			expectedReturnFields: []string{"address", "name", "network_view", "status"},
			expectedObjectType:   "discovery:status",
		},
		"DtcMonitorTcp": {
			obj:                  &DtcMonitorTcp{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:monitor:tcp",
		},
		"DtcObject": {
			obj:                  &DtcObject{},
			expectedReturnFields: []string{"abstract_type", "comment", "display_type", "name", "status"},
			expectedObjectType:   "dtc:object",
		},
		"DtcPool": {
			obj:                  &DtcPool{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:pool",
		},
		"DtcMonitorIcmp": {
			obj:                  &DtcMonitorIcmp{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:monitor:icmp",
		},
		"DtcRecordA": {
			obj:                  &DtcRecordA{},
			expectedReturnFields: []string{"dtc_server", "ipv4addr"},
			expectedObjectType:   "dtc:record:a",
		},
		"DtcRecordCname": {
			obj:                  &DtcRecordCname{},
			expectedReturnFields: []string{"canonical", "dtc_server"},
			expectedObjectType:   "dtc:record:cname",
		},
		"DtcRecordSrv": {
			obj:                  &DtcRecordSrv{},
			expectedReturnFields: []string{"dtc_server", "name", "port", "priority", "target", "weight"},
			expectedObjectType:   "dtc:record:srv",
		},
		"DtcTopology": {
			obj:                  &DtcTopology{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "dtc:topology",
		},
		"DtcServer": {
			obj:                  &DtcServer{},
			expectedReturnFields: []string{"comment", "host", "name"},
			expectedObjectType:   "dtc:server",
		},
		"DtcTopologyLabel": {
			obj:                  &DtcTopologyLabel{},
			expectedReturnFields: []string{"field", "label"},
			expectedObjectType:   "dtc:topology:label",
		},
		"DtcTopologyRule": {
			obj:                  &DtcTopologyRule{},
			expectedReturnFields: []string{},
			expectedObjectType:   "dtc:topology:rule",
		},
		"DtcRecordNaptr": {
			obj:                  &DtcRecordNaptr{},
			expectedReturnFields: []string{"dtc_server", "order", "preference", "regexp", "replacement", "services"},
			expectedObjectType:   "dtc:record:naptr",
		},
		"EADefinition": {
			obj:                  &EADefinition{},
			expectedReturnFields: []string{"comment", "default_value", "name", "type"},
			expectedObjectType:   "extensibleattributedef",
		},
		"DxlEndpoint": {
			obj:                  &DxlEndpoint{},
			expectedReturnFields: []string{"disable", "name", "outbound_member_type"},
			expectedObjectType:   "dxl:endpoint",
		},
		"Filterfingerprint": {
			obj:                  &Filterfingerprint{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "filterfingerprint",
		},
		"DtcRecordAaaa": {
			obj:                  &DtcRecordAaaa{},
			expectedReturnFields: []string{"dtc_server", "ipv6addr"},
			expectedObjectType:   "dtc:record:aaaa",
		},
		"Filtermac": {
			obj:                  &Filtermac{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "filtermac",
		},
		"Filternac": {
			obj:                  &Filternac{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "filternac",
		},
		"Fixedaddresstemplate": {
			obj:                  &Fixedaddresstemplate{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "fixedaddresstemplate",
		},
		"Ftpuser": {
			obj:                  &Ftpuser{},
			expectedReturnFields: []string{"username"},
			expectedObjectType:   "ftpuser",
		},
		"GridCloudapiCloudstatistics": {
			obj:                  &GridCloudapiCloudstatistics{},
			expectedReturnFields: []string{"allocated_available_ratio", "allocated_ip_count", "available_ip_count", "fixed_ip_count", "floating_ip_count", "tenant_count", "tenant_ip_count", "tenant_vm_count"},
			expectedObjectType:   "grid:cloudapi:cloudstatistics",
		},
		"Filteroption": {
			obj:                  &Filteroption{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "filteroption",
		},
		"Fileop": {
			obj:                  &Fileop{},
			expectedReturnFields: []string{},
			expectedObjectType:   "fileop",
		},
		"Fingerprint": {
			obj:                  &Fingerprint{},
			expectedReturnFields: []string{"comment", "device_class", "name"},
			expectedObjectType:   "fingerprint",
		},
		"Ipv4FixedAddress": {
			obj:                  &Ipv4FixedAddress{},
			expectedReturnFields: []string{"ipv4addr", "network_view"},
			expectedObjectType:   "fixedaddress",
		},
		"GridCloudapiTenant": {
			obj:                  &GridCloudapiTenant{},
			expectedReturnFields: []string{"comment", "id", "name"},
			expectedObjectType:   "grid:cloudapi:tenant",
		},
		"Filterrelayagent": {
			obj:                  &Filterrelayagent{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "filterrelayagent",
		},
		"GridCloudapi": {
			obj:                  &GridCloudapi{},
			expectedReturnFields: []string{"allow_api_admins", "allowed_api_admins", "enable_recycle_bin"},
			expectedObjectType:   "grid:cloudapi",
		},
		"GridDashboard": {
			obj:                  &GridDashboard{},
			expectedReturnFields: []string{"analytics_tunneling_event_critical_threshold", "analytics_tunneling_event_warning_threshold", "atp_critical_event_critical_threshold", "atp_critical_event_warning_threshold", "atp_major_event_critical_threshold", "atp_major_event_warning_threshold", "atp_warning_event_critical_threshold", "atp_warning_event_warning_threshold", "rpz_blocked_hit_critical_threshold", "rpz_blocked_hit_warning_threshold", "rpz_passthru_event_critical_threshold", "rpz_passthru_event_warning_threshold", "rpz_substituted_hit_critical_threshold", "rpz_substituted_hit_warning_threshold"},
			expectedObjectType:   "grid:dashboard",
		},
		"GridLicensePool": {
			obj:                  &GridLicensePool{},
			expectedReturnFields: []string{"type"},
			expectedObjectType:   "grid:license_pool",
		},
		"GridDhcpproperties": {
			obj:                  &GridDhcpproperties{},
			expectedReturnFields: []string{"disable_all_nac_filters", "grid"},
			expectedObjectType:   "grid:dhcpproperties",
		},
		"GridLicensePoolContainer": {
			obj:                  &GridLicensePoolContainer{},
			expectedReturnFields: []string{},
			expectedObjectType:   "grid:license_pool_container",
		},
		"GridCloudapiVm": {
			obj:                  &GridCloudapiVm{},
			expectedReturnFields: []string{"comment", "id", "name"},
			expectedObjectType:   "grid:cloudapi:vm",
		},
		"GridMemberCloudapi": {
			obj:                  &GridMemberCloudapi{},
			expectedReturnFields: []string{"allow_api_admins", "allowed_api_admins", "enable_service", "member", "status"},
			expectedObjectType:   "grid:member:cloudapi",
		},
		"GridFiledistribution": {
			obj:                  &GridFiledistribution{},
			expectedReturnFields: []string{"allow_uploads", "current_usage", "global_status", "name", "storage_limit"},
			expectedObjectType:   "grid:filedistribution",
		},
		"GridCloudapiVmaddress": {
			obj:                  &GridCloudapiVmaddress{},
			expectedReturnFields: []string{"address", "is_ipv4", "network_view", "port_id", "vm_name"},
			expectedObjectType:   "grid:cloudapi:vmaddress",
		},
		"GridServicerestartRequestChangedobject": {
			obj:                  &GridServicerestartRequestChangedobject{},
			expectedReturnFields: []string{"action", "changed_properties", "changed_time", "object_name", "object_type", "user_name"},
			expectedObjectType:   "grid:servicerestart:request:changedobject",
		},
		"GridServicerestartRequest": {
			obj:                  &GridServicerestartRequest{},
			expectedReturnFields: []string{"error", "group", "result", "state"},
			expectedObjectType:   "grid:servicerestart:request",
		},
		"GridServicerestartGroupOrder": {
			obj:                  &GridServicerestartGroupOrder{},
			expectedReturnFields: []string{},
			expectedObjectType:   "grid:servicerestart:group:order",
		},
		"GridDns": {
			obj:                  &GridDns{},
			expectedReturnFields: []string{},
			expectedObjectType:   "grid:dns",
		},
		"Grid": {
			obj:                  &Grid{},
			expectedReturnFields: []string{},
			expectedObjectType:   "grid",
		},
		"GridThreatanalytics": {
			obj:                  &GridThreatanalytics{},
			expectedReturnFields: []string{"enable_auto_download", "enable_scheduled_download", "module_update_policy", "name"},
			expectedObjectType:   "grid:threatanalytics",
		},
		"GridThreatprotection": {
			obj:                  &GridThreatprotection{},
			expectedReturnFields: []string{"grid_name"},
			expectedObjectType:   "grid:threatprotection",
		},
		"GridX509certificate": {
			obj:                  &GridX509certificate{},
			expectedReturnFields: []string{"issuer", "serial", "subject"},
			expectedObjectType:   "grid:x509certificate",
		},
		"Hostnamerewritepolicy": {
			obj:                  &Hostnamerewritepolicy{},
			expectedReturnFields: []string{"name", "replacement_character", "valid_characters"},
			expectedObjectType:   "hostnamerewritepolicy",
		},
		"GridServicerestartGroup": {
			obj:                  &GridServicerestartGroup{},
			expectedReturnFields: []string{"comment", "name", "service"},
			expectedObjectType:   "grid:servicerestart:group",
		},
		"HsmAllgroups": {
			obj:                  &HsmAllgroups{},
			expectedReturnFields: []string{"groups"},
			expectedObjectType:   "hsm:allgroups",
		},
		"HsmThalesgroup": {
			obj:                  &HsmThalesgroup{},
			expectedReturnFields: []string{"comment", "key_server_ip", "name"},
			expectedObjectType:   "hsm:thalesgroup",
		},
		"HsmSafenetgroup": {
			obj:                  &HsmSafenetgroup{},
			expectedReturnFields: []string{"comment", "hsm_version", "name"},
			expectedObjectType:   "hsm:safenetgroup",
		},
		"IpamStatistics": {
			obj:                  &IpamStatistics{},
			expectedReturnFields: []string{"cidr", "network", "network_view"},
			expectedObjectType:   "ipam:statistics",
		},
		"GridServicerestartStatus": {
			obj:                  &GridServicerestartStatus{},
			expectedReturnFields: []string{"failures", "finished", "grouped", "needed_restart", "no_restart", "parent", "pending", "pending_restart", "processing", "restarting", "success", "timeouts"},
			expectedObjectType:   "grid:servicerestart:status",
		},
		"Ipv6dhcpoptionspace": {
			obj:                  &Ipv6dhcpoptionspace{},
			expectedReturnFields: []string{"comment", "enterprise_number", "name"},
			expectedObjectType:   "ipv6dhcpoptionspace",
		},
		"Ipv6dhcpoptiondefinition": {
			obj:                  &Ipv6dhcpoptiondefinition{},
			expectedReturnFields: []string{"code", "name", "type"},
			expectedObjectType:   "ipv6dhcpoptiondefinition",
		},
		"GridMaxminddbinfo": {
			obj:                  &GridMaxminddbinfo{},
			expectedReturnFields: []string{"binary_major_version", "binary_minor_version", "build_time", "database_type", "deployment_time", "member", "topology_type"},
			expectedObjectType:   "grid:maxminddbinfo",
		},
		"Ipv6fixedaddresstemplate": {
			obj:                  &Ipv6fixedaddresstemplate{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "ipv6fixedaddresstemplate",
		},
		"Ipv6address": {
			obj:                  &Ipv6address{},
			expectedReturnFields: []string{"duid", "ip_address", "is_conflict", "lease_state", "names", "network", "network_view", "objects", "status", "types", "usage"},
			expectedObjectType:   "ipv6address",
		},
		"Ipv6networktemplate": {
			obj:                  &Ipv6networktemplate{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "ipv6networktemplate",
		},
		"Ipv6FixedAddress": {
			obj:                  &Ipv6FixedAddress{},
			expectedReturnFields: []string{"duid", "ipv6addr", "network_view"},
			expectedObjectType:   "ipv6fixedaddress",
		},
		"Ipv6range": {
			obj:                  &Ipv6range{},
			expectedReturnFields: []string{"comment", "end_addr", "network", "network_view", "start_addr"},
			expectedObjectType:   "ipv6range",
		},
		"Ipv4address": {
			obj:                  &Ipv4address{},
			expectedReturnFields: []string{"dhcp_client_identifier", "ip_address", "is_conflict", "lease_state", "mac_address", "names", "network", "network_view", "objects", "status", "types", "usage", "username"},
			expectedObjectType:   "ipv4address",
		},
		"LicenseGridwide": {
			obj:                  &LicenseGridwide{},
			expectedReturnFields: []string{"type"},
			expectedObjectType:   "license:gridwide",
		},
		"Kerberoskey": {
			obj:                  &Kerberoskey{},
			expectedReturnFields: []string{"domain", "enctype", "in_use", "principal", "version"},
			expectedObjectType:   "kerberoskey",
		},
		"Ipv6rangetemplate": {
			obj:                  &Ipv6rangetemplate{},
			expectedReturnFields: []string{"comment", "name", "number_of_addresses", "offset"},
			expectedObjectType:   "ipv6rangetemplate",
		},
		"Ipv6sharednetwork": {
			obj:                  &Ipv6sharednetwork{},
			expectedReturnFields: []string{"comment", "name", "network_view", "networks"},
			expectedObjectType:   "ipv6sharednetwork",
		},
		"Ipv6NetworkContainer": {
			obj:                  &Ipv6NetworkContainer{},
			expectedReturnFields: []string{"comment", "network", "network_view"},
			expectedObjectType:   "ipv6networkcontainer",
		},
		"Macfilteraddress": {
			obj:                  &Macfilteraddress{},
			expectedReturnFields: []string{"authentication_time", "comment", "expiration_time", "filter", "guest_custom_field1", "guest_custom_field2", "guest_custom_field3", "guest_custom_field4", "guest_email", "guest_first_name", "guest_last_name", "guest_middle_name", "guest_phone", "is_registered_user", "mac", "never_expires", "reserved_for_infoblox", "username"},
			expectedObjectType:   "macfilteraddress",
		},
		"LocaluserAuthservice": {
			obj:                  &LocaluserAuthservice{},
			expectedReturnFields: []string{"comment", "disabled", "name"},
			expectedObjectType:   "localuser:authservice",
		},
		"Lease": {
			obj:                  &Lease{},
			expectedReturnFields: []string{"address", "network_view"},
			expectedObjectType:   "lease",
		},
		"Mastergrid": {
			obj:                  &Mastergrid{},
			expectedReturnFields: []string{"address", "enable", "port"},
			expectedObjectType:   "mastergrid",
		},
		"MemberLicense": {
			obj:                  &MemberLicense{},
			expectedReturnFields: []string{"type"},
			expectedObjectType:   "member:license",
		},
		"MemberFiledistribution": {
			obj:                  &MemberFiledistribution{},
			expectedReturnFields: []string{"host_name", "ipv4_address", "ipv6_address", "status"},
			expectedObjectType:   "member:filedistribution",
		},
		"LdapAuthService": {
			obj:                  &LdapAuthService{},
			expectedReturnFields: []string{"comment", "disable", "ldap_user_attribute", "mode", "name"},
			expectedObjectType:   "ldap_auth_service",
		},
		"MemberThreatanalytics": {
			obj:                  &MemberThreatanalytics{},
			expectedReturnFields: []string{"host_name", "ipv4_address", "ipv6_address", "status"},
			expectedObjectType:   "member:threatanalytics",
		},
		"Memberdfp": {
			obj:                  &Memberdfp{},
			expectedReturnFields: []string{},
			expectedObjectType:   "memberdfp",
		},
		"MsserverAdsitesSite": {
			obj:                  &MsserverAdsitesSite{},
			expectedReturnFields: []string{"domain", "name"},
			expectedObjectType:   "msserver:adsites:site",
		},
		"MsserverAdsitesDomain": {
			obj:                  &MsserverAdsitesDomain{},
			expectedReturnFields: []string{"name", "netbios", "network_view"},
			expectedObjectType:   "msserver:adsites:domain",
		},
		"MemberDhcpproperties": {
			obj:                  &MemberDhcpproperties{},
			expectedReturnFields: []string{"host_name", "ipv4addr", "ipv6addr"},
			expectedObjectType:   "member:dhcpproperties",
		},
		"MsserverDhcp": {
			obj:                  &MsserverDhcp{},
			expectedReturnFields: []string{"address"},
			expectedObjectType:   "msserver:dhcp",
		},
		"Member": {
			obj:                  &Member{},
			expectedReturnFields: []string{"config_addr_type", "host_name", "platform", "service_type_configuration"},
			expectedObjectType:   "member",
		},
		"MemberThreatprotection": {
			obj:                  &MemberThreatprotection{},
			expectedReturnFields: []string{},
			expectedObjectType:   "member:threatprotection",
		},
		"MsserverDns": {
			obj:                  &MsserverDns{},
			expectedReturnFields: []string{"address"},
			expectedObjectType:   "msserver:dns",
		},
		"Namedacl": {
			obj:                  &Namedacl{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "namedacl",
		},
		"Mssuperscope": {
			obj:                  &Mssuperscope{},
			expectedReturnFields: []string{"disable", "name", "network_view"},
			expectedObjectType:   "mssuperscope",
		},
		"Msserver": {
			obj:                  &Msserver{},
			expectedReturnFields: []string{"address"},
			expectedObjectType:   "msserver",
		},
		"Natgroup": {
			obj:                  &Natgroup{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "natgroup",
		},
		"NotificationRestEndpoint": {
			obj:                  &NotificationRestEndpoint{},
			expectedReturnFields: []string{"name", "outbound_member_type", "uri"},
			expectedObjectType:   "notification:rest:endpoint",
		},
		"Ipv4NetworkContainer": {
			obj:                  &Ipv4NetworkContainer{},
			expectedReturnFields: []string{"comment", "network", "network_view"},
			expectedObjectType:   "networkcontainer",
		},
		"NetworkView": {
			obj:                  &NetworkView{},
			expectedReturnFields: []string{"comment", "is_default", "name"},
			expectedObjectType:   "networkview",
		},
		"MemberDns": {
			obj:                  &MemberDns{},
			expectedReturnFields: []string{"host_name", "ipv4addr", "ipv6addr"},
			expectedObjectType:   "member:dns",
		},
		"Ipv4Network": {
			obj:                  &Ipv4Network{},
			expectedReturnFields: []string{"comment", "network", "network_view"},
			expectedObjectType:   "network",
		},
		"NetworkDiscovery": {
			obj:                  &NetworkDiscovery{},
			expectedReturnFields: []string{},
			expectedObjectType:   "network_discovery",
		},
		"NotificationRestTemplate": {
			obj:                  &NotificationRestTemplate{},
			expectedReturnFields: []string{"content", "name"},
			expectedObjectType:   "notification:rest:template",
		},
		"MemberParentalcontrol": {
			obj:                  &MemberParentalcontrol{},
			expectedReturnFields: []string{"enable_service", "name"},
			expectedObjectType:   "member:parentalcontrol",
		},
		"NsgroupDelegation": {
			obj:                  &NsgroupDelegation{},
			expectedReturnFields: []string{"delegate_to", "name"},
			expectedObjectType:   "nsgroup:delegation",
		},
		"NotificationRule": {
			obj:                  &NotificationRule{},
			expectedReturnFields: []string{"event_type", "name", "notification_action", "notification_target"},
			expectedObjectType:   "notification:rule",
		},
		"NsgroupForwardingmember": {
			obj:                  &NsgroupForwardingmember{},
			expectedReturnFields: []string{"forwarding_servers", "name"},
			expectedObjectType:   "nsgroup:forwardingmember",
		},
		"Networktemplate": {
			obj:                  &Networktemplate{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "networktemplate",
		},
		"Networkuser": {
			obj:                  &Networkuser{},
			expectedReturnFields: []string{"address", "domainname", "name", "network_view", "user_status"},
			expectedObjectType:   "networkuser",
		},
		"NsgroupForwardstubserver": {
			obj:                  &NsgroupForwardstubserver{},
			expectedReturnFields: []string{"external_servers", "name"},
			expectedObjectType:   "nsgroup:forwardstubserver",
		},
		"NsgroupStubmember": {
			obj:                  &NsgroupStubmember{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "nsgroup:stubmember",
		},
		"Orderedranges": {
			obj:                  &Orderedranges{},
			expectedReturnFields: []string{"network", "ranges"},
			expectedObjectType:   "orderedranges",
		},
		"Orderedresponsepolicyzones": {
			obj:                  &Orderedresponsepolicyzones{},
			expectedReturnFields: []string{"view"},
			expectedObjectType:   "orderedresponsepolicyzones",
		},
		"OutboundCloudclient": {
			obj:                  &OutboundCloudclient{},
			expectedReturnFields: []string{"enable", "interval"},
			expectedObjectType:   "outbound:cloudclient",
		},
		"Nsgroup": {
			obj:                  &Nsgroup{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "nsgroup",
		},
		"ParentalcontrolAvp": {
			obj:                  &ParentalcontrolAvp{},
			expectedReturnFields: []string{"name", "type", "value_type"},
			expectedObjectType:   "parentalcontrol:avp",
		},
		"ParentalcontrolBlockingpolicy": {
			obj:                  &ParentalcontrolBlockingpolicy{},
			expectedReturnFields: []string{"name", "value"},
			expectedObjectType:   "parentalcontrol:blockingpolicy",
		},
		"ParentalcontrolIpspacediscriminator": {
			obj:                  &ParentalcontrolIpspacediscriminator{},
			expectedReturnFields: []string{"name", "value"},
			expectedObjectType:   "parentalcontrol:ipspacediscriminator",
		},
		"ParentalcontrolSubscribersite": {
			obj:                  &ParentalcontrolSubscribersite{},
			expectedReturnFields: []string{"block_size", "first_port", "name", "strict_nat"},
			expectedObjectType:   "parentalcontrol:subscribersite",
		},
		"Permission": {
			obj:                  &Permission{},
			expectedReturnFields: []string{"group", "permission", "resource_type", "role"},
			expectedObjectType:   "permission",
		},
		"Ipv6Network": {
			obj:                  &Ipv6Network{},
			expectedReturnFields: []string{"comment", "network", "network_view"},
			expectedObjectType:   "ipv6network",
		},
		"ParentalcontrolSubscriber": {
			obj:                  &ParentalcontrolSubscriber{},
			expectedReturnFields: []string{"alt_subscriber_id", "local_id", "subscriber_id"},
			expectedObjectType:   "parentalcontrol:subscriber",
		},
		"ParentalcontrolSubscriberrecord": {
			obj:                  &ParentalcontrolSubscriberrecord{},
			expectedReturnFields: []string{"accounting_session_id", "ip_addr", "ipsd", "localid", "prefix", "site", "subscriber_id"},
			expectedObjectType:   "parentalcontrol:subscriberrecord",
		},
		"Rangetemplate": {
			obj:                  &Rangetemplate{},
			expectedReturnFields: []string{"comment", "name", "number_of_addresses", "offset"},
			expectedObjectType:   "rangetemplate",
		},
		"PxgridEndpoint": {
			obj:                  &PxgridEndpoint{},
			expectedReturnFields: []string{"address", "disable", "name", "outbound_member_type"},
			expectedObjectType:   "pxgrid:endpoint",
		},
		"RadiusAuthservice": {
			obj:                  &RadiusAuthservice{},
			expectedReturnFields: []string{"comment", "disable", "name"},
			expectedObjectType:   "radius:authservice",
		},
		"Range": {
			obj:                  &Range{},
			expectedReturnFields: []string{"comment", "end_addr", "network", "network_view", "start_addr"},
			expectedObjectType:   "range",
		},
		"RecordAAAA": {
			obj:                  &RecordAAAA{},
			expectedReturnFields: []string{"ipv6addr", "name", "view"},
			expectedObjectType:   "record:aaaa",
		},
		"RecordDhcid": {
			obj:                  &RecordDhcid{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:dhcid",
		},
		"RecordA": {
			obj:                  &RecordA{},
			expectedReturnFields: []string{"ipv4addr", "name", "view"},
			expectedObjectType:   "record:a",
		},
		"RecordDnskey": {
			obj:                  &RecordDnskey{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:dnskey",
		},
		"RecordDname": {
			obj:                  &RecordDname{},
			expectedReturnFields: []string{"name", "target", "view"},
			expectedObjectType:   "record:dname",
		},
		"RecordCaa": {
			obj:                  &RecordCaa{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:caa",
		},
		"RecordDtclbdn": {
			obj:                  &RecordDtclbdn{},
			expectedReturnFields: []string{"comment", "name", "view", "zone"},
			expectedObjectType:   "record:dtclbdn",
		},
		"HostRecord": {
			obj:                  &HostRecord{},
			expectedReturnFields: []string{"ipv4addrs", "ipv6addrs", "name", "view"},
			expectedObjectType:   "record:host",
		},
		"RecordCNAME": {
			obj:                  &RecordCNAME{},
			expectedReturnFields: []string{"canonical", "name", "view"},
			expectedObjectType:   "record:cname",
		},
		"RecordMx": {
			obj:                  &RecordMx{},
			expectedReturnFields: []string{"mail_exchanger", "name", "preference", "view"},
			expectedObjectType:   "record:mx",
		},
		"RecordNsec": {
			obj:                  &RecordNsec{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:nsec",
		},
		"HostRecordIpv4Addr": {
			obj:                  &HostRecordIpv4Addr{},
			expectedReturnFields: []string{"configure_for_dhcp", "host", "ipv4addr", "mac"},
			expectedObjectType:   "record:host_ipv4addr",
		},
		"RecordNsec3param": {
			obj:                  &RecordNsec3param{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:nsec3param",
		},
		"RecordNS": {
			obj:                  &RecordNS{},
			expectedReturnFields: []string{"name", "nameserver", "view"},
			expectedObjectType:   "record:ns",
		},
		"RecordDs": {
			obj:                  &RecordDs{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:ds",
		},
		"RecordRpzA": {
			obj:                  &RecordRpzA{},
			expectedReturnFields: []string{"ipv4addr", "name", "view"},
			expectedObjectType:   "record:rpz:a",
		},
		"RecordRpzAIpaddress": {
			obj:                  &RecordRpzAIpaddress{},
			expectedReturnFields: []string{"ipv4addr", "name", "view"},
			expectedObjectType:   "record:rpz:a:ipaddress",
		},
		"HostRecordIpv6Addr": {
			obj:                  &HostRecordIpv6Addr{},
			expectedReturnFields: []string{"configure_for_dhcp", "duid", "host", "ipv6addr"},
			expectedObjectType:   "record:host_ipv6addr",
		},
		"RecordAlias": {
			obj:                  &RecordAlias{},
			expectedReturnFields: []string{"name", "target_name", "target_type", "view"},
			expectedObjectType:   "record:alias",
		},
		"RecordRpzAaaa": {
			obj:                  &RecordRpzAaaa{},
			expectedReturnFields: []string{"ipv6addr", "name", "view"},
			expectedObjectType:   "record:rpz:aaaa",
		},
		"RecordNaptr": {
			obj:                  &RecordNaptr{},
			expectedReturnFields: []string{"name", "order", "preference", "regexp", "replacement", "services", "view"},
			expectedObjectType:   "record:naptr",
		},
		"RecordNsec3": {
			obj:                  &RecordNsec3{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:nsec3",
		},
		"RecordRpzAaaaIpaddress": {
			obj:                  &RecordRpzAaaaIpaddress{},
			expectedReturnFields: []string{"ipv6addr", "name", "view"},
			expectedObjectType:   "record:rpz:aaaa:ipaddress",
		},
		"RecordPTR": {
			obj:                  &RecordPTR{},
			expectedReturnFields: []string{"ptrdname", "view"},
			expectedObjectType:   "record:ptr",
		},
		"RecordRpzCnameClientipaddressdn": {
			obj:                  &RecordRpzCnameClientipaddressdn{},
			expectedReturnFields: []string{"canonical", "name", "view"},
			expectedObjectType:   "record:rpz:cname:clientipaddressdn",
		},
		"RecordRpzCnameClientipaddress": {
			obj:                  &RecordRpzCnameClientipaddress{},
			expectedReturnFields: []string{"canonical", "name", "view"},
			expectedObjectType:   "record:rpz:cname:clientipaddress",
		},
		"RecordRpzCname": {
			obj:                  &RecordRpzCname{},
			expectedReturnFields: []string{"canonical", "name", "view"},
			expectedObjectType:   "record:rpz:cname",
		},
		"RecordRpzNaptr": {
			obj:                  &RecordRpzNaptr{},
			expectedReturnFields: []string{"name", "order", "preference", "regexp", "replacement", "services", "view"},
			expectedObjectType:   "record:rpz:naptr",
		},
		"RecordRpzCnameIpaddressdn": {
			obj:                  &RecordRpzCnameIpaddressdn{},
			expectedReturnFields: []string{"canonical", "name", "view"},
			expectedObjectType:   "record:rpz:cname:ipaddressdn",
		},
		"RecordRpzMx": {
			obj:                  &RecordRpzMx{},
			expectedReturnFields: []string{"mail_exchanger", "name", "preference", "view"},
			expectedObjectType:   "record:rpz:mx",
		},
		"RecordRpzPtr": {
			obj:                  &RecordRpzPtr{},
			expectedReturnFields: []string{"ptrdname", "view"},
			expectedObjectType:   "record:rpz:ptr",
		},
		"RecordRpzSrv": {
			obj:                  &RecordRpzSrv{},
			expectedReturnFields: []string{"name", "port", "priority", "target", "view", "weight"},
			expectedObjectType:   "record:rpz:srv",
		},
		"RecordRpzTxt": {
			obj:                  &RecordRpzTxt{},
			expectedReturnFields: []string{"name", "text", "view"},
			expectedObjectType:   "record:rpz:txt",
		},
		"RecordRrsig": {
			obj:                  &RecordRrsig{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:rrsig",
		},
		"Recordnamepolicy": {
			obj:                  &Recordnamepolicy{},
			expectedReturnFields: []string{"is_default", "name", "regex"},
			expectedObjectType:   "recordnamepolicy",
		},
		"RecordTlsa": {
			obj:                  &RecordTlsa{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:tlsa",
		},
		"RecordUnknown": {
			obj:                  &RecordUnknown{},
			expectedReturnFields: []string{"name", "view"},
			expectedObjectType:   "record:unknown",
		},
		"RecordRpzCnameIpaddress": {
			obj:                  &RecordRpzCnameIpaddress{},
			expectedReturnFields: []string{"canonical", "name", "view"},
			expectedObjectType:   "record:rpz:cname:ipaddress",
		},
		"Restartservicestatus": {
			obj:                  &Restartservicestatus{},
			expectedReturnFields: []string{"dhcp_status", "dns_status", "member", "reporting_status"},
			expectedObjectType:   "restartservicestatus",
		},
		"RecordSrv": {
			obj:                  &RecordSrv{},
			expectedReturnFields: []string{"name", "port", "priority", "target", "view", "weight"},
			expectedObjectType:   "record:srv",
		},
		"Rir": {
			obj:                  &Rir{},
			expectedReturnFields: []string{"communication_mode", "email", "name", "url"},
			expectedObjectType:   "rir",
		},
		"RirOrganization": {
			obj:                  &RirOrganization{},
			expectedReturnFields: []string{"id", "maintainer", "name", "rir", "sender_email"},
			expectedObjectType:   "rir:organization",
		},
		"Ruleset": {
			obj:                  &Ruleset{},
			expectedReturnFields: []string{"comment", "disabled", "name", "type"},
			expectedObjectType:   "ruleset",
		},
		"SamlAuthservice": {
			obj:                  &SamlAuthservice{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "saml:authservice",
		},
		"RecordTXT": {
			obj:                  &RecordTXT{},
			expectedReturnFields: []string{"name", "text", "view"},
			expectedObjectType:   "record:txt",
		},
		"Search": {
			obj:                  &Search{},
			expectedReturnFields: []string{},
			expectedObjectType:   "search",
		},
		"Scavengingtask": {
			obj:                  &Scavengingtask{},
			expectedReturnFields: []string{"action", "associated_object", "status"},
			expectedObjectType:   "scavengingtask",
		},
		"Roaminghost": {
			obj:                  &Roaminghost{},
			expectedReturnFields: []string{"address_type", "name", "network_view"},
			expectedObjectType:   "roaminghost",
		},
		"SharedrecordA": {
			obj:                  &SharedrecordA{},
			expectedReturnFields: []string{"ipv4addr", "name", "shared_record_group"},
			expectedObjectType:   "sharedrecord:a",
		},
		"Sharednetwork": {
			obj:                  &Sharednetwork{},
			expectedReturnFields: []string{"comment", "name", "network_view", "networks"},
			expectedObjectType:   "sharednetwork",
		},
		"SharedrecordAaaa": {
			obj:                  &SharedrecordAaaa{},
			expectedReturnFields: []string{"ipv6addr", "name", "shared_record_group"},
			expectedObjectType:   "sharedrecord:aaaa",
		},
		"SharedrecordCname": {
			obj:                  &SharedrecordCname{},
			expectedReturnFields: []string{"canonical", "name", "shared_record_group"},
			expectedObjectType:   "sharedrecord:cname",
		},
		"SharedrecordMx": {
			obj:                  &SharedrecordMx{},
			expectedReturnFields: []string{"mail_exchanger", "name", "preference", "shared_record_group"},
			expectedObjectType:   "sharedrecord:mx",
		},
		"SharedrecordSrv": {
			obj:                  &SharedrecordSrv{},
			expectedReturnFields: []string{"name", "port", "priority", "shared_record_group", "target", "weight"},
			expectedObjectType:   "sharedrecord:srv",
		},
		"Sharedrecordgroup": {
			obj:                  &Sharedrecordgroup{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "sharedrecordgroup",
		},
		"SmartfolderChildren": {
			obj:                  &SmartfolderChildren{},
			expectedReturnFields: []string{"resource", "value", "value_type"},
			expectedObjectType:   "smartfolder:children",
		},
		"SharedrecordTxt": {
			obj:                  &SharedrecordTxt{},
			expectedReturnFields: []string{"name", "shared_record_group", "text"},
			expectedObjectType:   "sharedrecord:txt",
		},
		"SmartfolderGlobal": {
			obj:                  &SmartfolderGlobal{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "smartfolder:global",
		},
		"Scheduledtask": {
			obj:                  &Scheduledtask{},
			expectedReturnFields: []string{"approval_status", "execution_status", "task_id"},
			expectedObjectType:   "scheduledtask",
		},
		"Snmpuser": {
			obj:                  &Snmpuser{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "snmpuser",
		},
		"Superhostchild": {
			obj:                  &Superhostchild{},
			expectedReturnFields: []string{"comment", "data", "name", "network_view", "parent", "record_parent", "type", "view"},
			expectedObjectType:   "superhostchild",
		},
		"Superhost": {
			obj:                  &Superhost{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "superhost",
		},
		"Taxii": {
			obj:                  &Taxii{},
			expectedReturnFields: []string{"ipv4addr", "ipv6addr", "name"},
			expectedObjectType:   "taxii",
		},
		"ThreatanalyticsModuleset": {
			obj:                  &ThreatanalyticsModuleset{},
			expectedReturnFields: []string{"version"},
			expectedObjectType:   "threatanalytics:moduleset",
		},
		"ThreatanalyticsAnalyticsWhitelist": {
			obj:                  &ThreatanalyticsAnalyticsWhitelist{},
			expectedReturnFields: []string{"version"},
			expectedObjectType:   "threatanalytics:analytics_whitelist",
		},
		"Tftpfiledir": {
			obj:                  &Tftpfiledir{},
			expectedReturnFields: []string{"directory", "name", "type"},
			expectedObjectType:   "tftpfiledir",
		},
		"SyslogEndpoint": {
			obj:                  &SyslogEndpoint{},
			expectedReturnFields: []string{"name", "outbound_member_type"},
			expectedObjectType:   "syslog:endpoint",
		},
		"ThreatanalyticsWhitelist": {
			obj:                  &ThreatanalyticsWhitelist{},
			expectedReturnFields: []string{"comment", "disable", "fqdn"},
			expectedObjectType:   "threatanalytics:whitelist",
		},
		"SmartfolderPersonal": {
			obj:                  &SmartfolderPersonal{},
			expectedReturnFields: []string{"comment", "is_shortcut", "name"},
			expectedObjectType:   "smartfolder:personal",
		},
		"ThreatprotectionGridRule": {
			obj:                  &ThreatprotectionGridRule{},
			expectedReturnFields: []string{"name", "ruleset", "sid"},
			expectedObjectType:   "threatprotection:grid:rule",
		},
		"ThreatprotectionRule": {
			obj:                  &ThreatprotectionRule{},
			expectedReturnFields: []string{"member", "rule"},
			expectedObjectType:   "threatprotection:rule",
		},
		"ThreatprotectionProfileRule": {
			obj:                  &ThreatprotectionProfileRule{},
			expectedReturnFields: []string{"profile", "rule"},
			expectedObjectType:   "threatprotection:profile:rule",
		},
		"ThreatprotectionRuleset": {
			obj:                  &ThreatprotectionRuleset{},
			expectedReturnFields: []string{"add_type", "version"},
			expectedObjectType:   "threatprotection:ruleset",
		},
		"ThreatprotectionRuletemplate": {
			obj:                  &ThreatprotectionRuletemplate{},
			expectedReturnFields: []string{"name", "ruleset", "sid"},
			expectedObjectType:   "threatprotection:ruletemplate",
		},
		"ThreatprotectionStatistics": {
			obj:                  &ThreatprotectionStatistics{},
			expectedReturnFields: []string{"member", "stat_infos"},
			expectedObjectType:   "threatprotection:statistics",
		},
		"TacacsplusAuthservice": {
			obj:                  &TacacsplusAuthservice{},
			expectedReturnFields: []string{"comment", "disable", "name"},
			expectedObjectType:   "tacacsplus:authservice",
		},
		"Upgradegroup": {
			obj:                  &Upgradegroup{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "upgradegroup",
		},
		"ThreatprotectionRulecategory": {
			obj:                  &ThreatprotectionRulecategory{},
			expectedReturnFields: []string{"name", "ruleset"},
			expectedObjectType:   "threatprotection:rulecategory",
		},
		"Upgradeschedule": {
			obj:                  &Upgradeschedule{},
			expectedReturnFields: []string{"active", "start_time", "time_zone"},
			expectedObjectType:   "upgradeschedule",
		},
		"ThreatprotectionProfile": {
			obj:                  &ThreatprotectionProfile{},
			expectedReturnFields: []string{"comment", "name"},
			expectedObjectType:   "threatprotection:profile",
		},
		"UpgradeStatus": {
			obj:                  &UpgradeStatus{},
			expectedReturnFields: []string{"alternate_version", "comment", "current_version", "distribution_version", "element_status", "grid_state", "group_state", "ha_status", "hotfixes", "ipv4_address", "ipv6_address", "member", "message", "pnode_role", "reverted", "status_value", "status_value_update_time", "steps", "steps_completed", "steps_total", "type", "upgrade_group", "upgrade_state", "upgrade_test_status", "upload_version"},
			expectedObjectType:   "upgradestatus",
		},
		"ThreatinsightCloudclient": {
			obj:                  &ThreatinsightCloudclient{},
			expectedReturnFields: []string{"enable", "interval"},
			expectedObjectType:   "threatinsight:cloudclient",
		},
		"Vlan": {
			obj:                  &Vlan{},
			expectedReturnFields: []string{"id", "name", "parent"},
			expectedObjectType:   "vlan",
		},
		"Vdiscoverytask": {
			obj:                  &Vdiscoverytask{},
			expectedReturnFields: []string{"name", "state"},
			expectedObjectType:   "vdiscoverytask",
		},
		"Vlanview": {
			obj:                  &Vlanview{},
			expectedReturnFields: []string{"end_vlan_id", "name", "start_vlan_id"},
			expectedObjectType:   "vlanview",
		},
		"Vlanrange": {
			obj:                  &Vlanrange{},
			expectedReturnFields: []string{"end_vlan_id", "name", "start_vlan_id", "vlan_view"},
			expectedObjectType:   "vlanrange",
		},
		"ZoneAuthDiscrepancy": {
			obj:                  &ZoneAuthDiscrepancy{},
			expectedReturnFields: []string{"description", "severity", "timestamp", "zone"},
			expectedObjectType:   "zone_auth_discrepancy",
		},
		"UserProfile": {
			obj:                  &UserProfile{},
			expectedReturnFields: []string{"name"},
			expectedObjectType:   "userprofile",
		},
		"View": {
			obj:                  &View{},
			expectedReturnFields: []string{"comment", "is_default", "name"},
			expectedObjectType:   "view",
		},
		"ZoneDelegated": {
			obj:                  &ZoneDelegated{},
			expectedReturnFields: []string{"delegate_to", "fqdn", "view"},
			expectedObjectType:   "zone_delegated",
		},
		"ZoneStub": {
			obj:                  &ZoneStub{},
			expectedReturnFields: []string{"fqdn", "stub_from", "view"},
			expectedObjectType:   "zone_stub",
		},
		"ZoneForward": {
			obj:                  &ZoneForward{},
			expectedReturnFields: []string{"forward_to", "fqdn", "view"},
			expectedObjectType:   "zone_forward",
		},
		"ZoneAuth": {
			obj:                  &ZoneAuth{},
			expectedReturnFields: []string{"fqdn", "view"},
			expectedObjectType:   "zone_auth",
		},
		"ZoneRp": {
			obj:                  &ZoneRp{},
			expectedReturnFields: []string{"fqdn", "view"},
			expectedObjectType:   "zone_rp",
		},
	}

	for name, tc := range testCases {
		t.Run(name, func(t *testing.T) {
			g := NewGomegaWithT(t)
			// Check if default return fields are valid
			g.Expect(tc.obj.ReturnFields()).To(Equal(tc.expectedReturnFields))
			// Check if ObjectType is valid
			g.Expect(tc.obj.ObjectType()).To(Equal(tc.expectedObjectType))
		})
	}
}
